branch-defaults:
  default:
    environment: frontend

environment-defaults:
  frontend:
    branch: null
    repository: null

global:
  application_name: conchayoro
  default_ec2_keyname: vockey
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: LabInstanceProfile
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application

Inclua o arquivo frontend/Dockerrun.aws.json.
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/<PROJECT_NAME>/<MODULE_NAME>:<TAG>",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": "80"
    }
  ]
}
